export { OnboardingTemplate } from './OnboardingTemplate/OnboardingTemplate';
export { SignInTemplate } from './SignInTemplate/SignInTemplate';
export { DashboardTemplate } from './DashboardTemplate/DashboardTemplate';
export { MobilePaymentTemplate } from './MobilePaymentTemplate/MobilePaymentTemplate';
export { SuccessPaymentTemplate } from './SuccessPaymentTemplate/SuccessPaymentTemplate';
export { TransactionDetailsTemplate } from './TransactionDetailsTemplate/TransactionDetailsTemplate';
export { ChangePasswordTemplate } from './ChangePasswordTemplate/ChangePasswordTemplate';
export { SignUpTemplate } from './SignUpTemplate/SignUpTemplate';
export { SuccessRegistrationTemplate } from './SuccessRegistrationTemplate/SuccessRegistrationTemplate';
